services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: verySecretPassword
      POSTGRES_USER: administrator
      POSTGRES_DB: todo
    # The "could not open directory pg_notify: No such file or directory" error 
    # usually happens when your PostgreSQL data directory is corrupted or incomplete.
    # The error message "PostgreSQL Database directory appears to contain a database; 
    # Skipping initialization" shows that PostgreSQL is trying to use an existing database but finding it corrupted
    # or missing a file. 
    # Comment out or rename the volume to force a fresh initialization
    # Once it works,  you can uncomment the volumes line, 
    # but you'll need to make sure the local directory is empty first, so PostgreSQL can initialize it properly.
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U administrator -d todo"]
      interval: 5s
      retries: 10
      start_period: 60s
      timeout: 20s
  app:
    build: .
    restart: always
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql:\
        //administrator:verySecretPassword@database:5432/todo"
    ports:
      - "6400:6400"
    depends_on:
      database:
        condition: service_healthy
        restart: true